# Numerical Computing (NumPy) - Problem set

## Exercise 1: Manipulating a 3D Array

Create a 3D array with dimensions $3 \times 3 \times 3$ filled with random integers between 1 and 100. 
1. Replace all values that are divisible by 3 with -1.
2. Calculate the mean value for each of the three 2D layers in the 3D array.

In [5]:
# Your code
import numpy as np

# a = np.random.randint(1,101, 27).reshape((3,3,3))
a = np.random.randint(1,101, size = (3,3,3))
a

array([[[42, 13, 80],
        [26, 30, 18],
        [74, 85, 89]],

       [[54, 60, 20],
        [51,  3,  7],
        [69, 41, 10]],

       [[87, 74, 12],
        [ 4, 92, 61],
        [66, 12, 68]]])

In [9]:
a[a%3 == 0] = -1
a == np.where(a%3==0, -1, a)

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [14]:
a.mean(axis=(0,1))

array([10.88888889, 33.44444444, 37.        ])

In [13]:
a[0].mean()

40.44444444444444

## Exercise 2: Boolean Indexing and Filtering

Given an array of random integers between 1 and 50 (size 20):
1. Identify all elements that are prime numbers.
2. Replace all prime numbers with 0.

In [15]:
# Your code
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n%i == 0:
            return False
    return True

In [28]:
a_original = np.random.randint(1, 51, 20)

In [29]:
a_original

array([25, 14, 33, 21, 15, 22, 46,  9,  5, 47, 18, 45, 37,  4, 36, 12, 19,
       49, 34, 15])

In [22]:
a_prime = np.vectorize(is_prime)(a)

array([ True, False, False,  True, False, False, False, False,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False])

In [30]:
# a_prime = np.array([is_prime(x) for x in a])
a_prime = np.array([0 if is_prime(x) else x for x in a_original])
a_prime

array([25, 14, 33, 21, 15, 22, 46,  9,  0,  0, 18, 45,  0,  4, 36, 12,  0,
       49, 34, 15])

In [23]:
np.where(a_prime, 0, a)

array([ 0, 42, 12,  0, 49, 36, 25, 20,  0,  0,  9,  0, 50, 50,  0,  0,  0,
        0, 32, 35])

In [25]:
a[a_prime] = 0
a

array([ 0, 42, 12,  0, 49, 36, 25, 20,  0,  0,  9,  0, 50, 50,  0,  0,  0,
        0, 32, 35])

## Exercise 3: Array Manipulation and Reshaping

Create a 1D NumPy array of size 30 filled with random integers between 10 and 100. Perform the following:
1. Reshape the array into a $5 \times 6$ matrix.
2. Compute the sum of the values in each row.
3. Compute the sum of the values in each column.

In [1]:
# Your code

## Exercise 4: Matrix Determinant and Inverse

Generate a $4 \times 4$ matrix of random integers between 1 and 10. 
1. Calculate the **determinant** of the matrix.
2. If the determinant is non-zero, compute its **inverse**.
3. Verify that the inverse and the original matrix product result in an identity matrix.

Use functions:
- `np.linalg.det()`
- `np.linalg.inv()`
- `np.dot()`

In [1]:
# Your code

## Exercise 5: Simulating an Ornstein-Uhlenbeck Process

Simulate an **Ornstein-Uhlenbeck** process, which is used in finance to model mean-reverting processes such as interest rates. The formula is given by:

$$
X_{t+1} = X_t + \theta (\mu - X_t) \Delta t + \sigma \sqrt{\Delta t} \cdot Z_t
$$

Where:
- $X_t$ is the value of the process at time step $t$.
- $\theta$ is the speed of mean reversion (how fast the process reverts to the mean).
- $\mu$ is the long-term mean to which the process reverts.
- $\sigma$ is the volatility or standard deviation of the process.
- $\Delta t$ is the time step size (in this case, 0.01).
- $Z_t$ is a random normal variable ($Z_t \sim N(0, 1)$), representing the random noise at each time step.

**Background information:**
1. **Mean-reverting drift**: $\theta (\mu - X_t) \Delta t$
   - This term controls how quickly the process moves back towards the mean $\mu$.
   - The strength of this pull towards the mean is determined by $\theta$, and the distance from the mean is represented by $\mu - X_t$.

2. **Random fluctuation**: $\sigma \sqrt{\Delta t} \cdot Z_t$
   - This term represents the stochastic component of the process, introducing random fluctuations.
   - $\sigma$ controls the magnitude of these fluctuations, while $\sqrt{\Delta t}$ ensures the appropriate scaling over time steps.

Thus, at each time step $t$, the process evolves according to this combination of mean-reverting behavior and random fluctuation.


**Parameter setting for the simulation:**
  - $ \theta = 0.7 $ (mean reversion speed),
  - $ \mu = 0.05 $ (long-term mean),
  - $ \sigma = 0.15 $ (volatility),
  - $ dt = 0.01 $ (time step),
  - initial value $ X_0 = 0.05 $,
  - simulate for 500 time steps.

In [1]:
# Your code

## Exercise 6: Element-Wise Operations on Multiple Arrays

Create two arrays, `A` and `B`, each of size \(1000\), with random values between 1 and 10. Perform the following operations:
1. Identify the indices where elements of `A` are larger than the corresponding elements in `B`.
2. Compute a new array `C` where `C[i]` equals the value of `A[i]` if `A[i] > B[i]`, otherwise it equals the average of `A[i]` and `B[i]`.

In [1]:
# Your code

## Exercise 7: Matrix Operations and Transposing

Given a $4 \times 4$ matrix filled with random integers between 1 and 20, perform the following:

1. Transpose the matrix.
2. Compute the sum of the elements in the original matrix.
3. Compute the sum of the elements in the transposed matrix.
4. Verify if the sum of elements in the original and transposed matrix are equal.

## Exercise 8: Advanced Matrix Operations and Broadcasting

Given two matrices  A  and  B  with dimensions $3 \times 3$ filled with random integers between 1 and 10:

1. Add the two matrices together using broadcasting.
2. Multiply the two matrices element-wise.
3. Compute the matrix product of  A  and  B  using matrix multiplication.
4. Subtract the transpose of matrix  B  from matrix  A .

---

## Exercise 9: Function Application with Vectorization

Write a NumPy-based function that calculates the following for each element of a 1D array:


$$f(x) = 3x^2 + 2x - 5$$

1. Create a 1D array of size 20 with random integers between -10 and 10.
2. Apply the function f(x) to each element of the array in a vectorized manner (without using loops).
3. Return the resulting array.

## Exercise 10: Advanced Broadcasting and Boolean Filtering

Given a $6 \times 6$ matrix of random integers between 1 and 100:

1. Write a function that finds all the elements divisible by both 3 and 5.
2. Replace all such elements with -1 using boolean filtering and broadcasting.
3. Return the modified matrix.

---